# Numpy

Numpy is a library for scientific computing with Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures.

It would be beyond the scope of this course to cover all of Numpy's features in detail.

Therefore, we will only cover the absolute basics here.

In [1]:
import numpy as np

##  Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called `ndarray`.

We can create a NumPy `ndarray` object by using the `array()` function.

### Example

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

## Shape of an Array

The shape of an array is the number of elements in each dimension.

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)



`type()`: This built-in Python function tells us the type of the object passed to it. Like in the above code, it shows that `arr` is of `numpy.ndarray` type.

To create an `ndarray`, we can pass a list, tuple, or any array-like object into the `array()` method, and it will be converted into an `ndarray`.


## Multidimensional Arrays

Numpy can handle n-dimensional arrays. An image for example has two dimensions. Or does it?

A grayscale image has the shape of (height, width) - so 2 dimensions. Notice that in numpy, the height is in the first dimension.\
A RGB (color) image has the shape of (height, width, 3) - so 3 dimensions. The third dimension represents the three color channels: red, green, and blue.

If the last dimension is a single element, it can be omitted. For example, a grayscale image can be represented as (height, width, 1) or (height, width).\
There is a small difference between the two representations. The former contains only the single element in its last dimension (for example an integer), while the latter contains an array with one element (for example an integer).

If we are sophistical, we could also argue that each element in the RGB channel has a dimension of size 1 and therefore the shape of an RGB image should be (height, width, 3, 1). You see where this is going... This will only pack the single element in an array again, and we could go on an on with the game. So, as soon a dimension has the size 1, it is ignored as a dimension to prevent puting its element into an array.

Here's an example:



In [ ]:
# Black grayscale image
grayscale_image = np.zeros((3, 4), dtype=np.uint8)
print(grayscale_image)

In [ ]:
grayscale_image = np.zeros((3, 4, 1), dtype=np.uint8)
print(grayscale_image)

As you can see, the zeros in the second image of shape (3, 4, 1) are just packed in an array, which is unnecessary.

For an RGB image it is necessary: instead of a zero, it is an array of size 3: red, green, blue.

In [ ]:
rgb_image = np.zeros((3, 4, 3), dtype=np.uint8)
print(rgb_image)

## Indexing

Indexing could be a standalone course in itself, but here are some examples on how to access numpy arrays:

In [6]:
arr = np.array(np.arange(12)).reshape(3, 4)
print(arr)
print()
print(f'{arr[0, 0]=}')
print(f'{arr[1, 0]=}')
print(f'{arr[2, -1]=}')
print(f'{arr[2, -2]=}')
print(f'{arr[1, :]=}')
print(f'{arr[:, 1]=}')
print(f'{arr[1, 1:3]=}')
print(f'{arr[1, 1:]=}')
print(f'{arr[1, :-1]=}')
print(f'{arr[1, ::2]=}')
print(f'{arr[1, ::-1]=}')
print(f'{arr[1, ::-2]=}')
arr = np.array(np.arange(12)).reshape(2, 2, 3)
print()
print(arr)
print()
print(f'{arr[..., 0]=}') # ... means all the dimensions before the specified one


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

arr[0, 0]=0
arr[1, 0]=4
arr[2, -1]=11
arr[2, -2]=10
arr[1, :]=array([4, 5, 6, 7])
arr[:, 1]=array([1, 5, 9])
arr[1, 1:3]=array([5, 6])
arr[1, 1:]=array([5, 6, 7])
arr[1, :-1]=array([4, 5, 6])
arr[1, ::2]=array([4, 6])
arr[1, ::-1]=array([7, 6, 5, 4])
arr[1, ::-2]=array([7, 5])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

arr[..., 0]=array([[0, 3],
       [6, 9]])


In [ ]:
# And here are some examples of how to write to the elements of an array:
arr = np.zeros((3, 4), dtype=np.uint16)
arr[0, 0] = 100
print(arr)
print()
arr[1, 0] = 200
print(arr)
print()
arr[1, :] = 500
print(arr)
print()
arr[1, :] = [1, 2, 3, 4]
print(arr)
print()
arr[1, 1:3] = 700
print(arr)

## Masking

Here as well: you can do much more than shown here. But in this course, a simple example:

In [ ]:
arr = np.array([1, 1, 0, 1, 8, 0, 9, 1], dtype=np.uint8)
mask = arr == 1
print(mask)
print(arr[mask])
arr[mask] = 5
print(arr)
print(arr[arr > 5])
arr[arr > 5] *= 2
print(arr)
mask = arr > 5
arr[mask] = np.arange(len(arr[mask])) + 100
print(arr)


## Operations on the arrays

It is also possible to use arithmetical operations with arrays:

In [ ]:
arr = np.zeros((3, 4), dtype=np.uint16)
print(arr)
print()
arr += 5
print(arr)
print()
arr[1, :] *= 2
print(arr)
print()
arr -= 1
print(arr)
print()
arr[2, :] = arr[1, :] + arr[2, :]
print(arr)



## Ndarray specific class functions

You already stumbled over the `reshape` class function. Let's look at some simpler functions:

In [ ]:
# On arrays with more than one dimension, you can use the axis parameter to specify the axis along which you want to perform the operation.
arr = np.array(np.arange(12)).reshape(3, 4)
print(arr)
print()
print(f'{arr.sum()=}')
print(f'{arr.sum(axis=0)=}')
print(f'{arr.sum(axis=1)=}')
print(f'{arr.mean()=}')
print(f'{arr.mean(axis=0)=}')
print(f'{arr.mean(axis=1)=}')
print(f'{arr.std()=}')
print(f'{arr.std(axis=0)=}')
print(f'{arr.std(axis=1)=}')
print(f'{arr.min()=}')
print(f'{arr.min(axis=0)=}')

## Exercise

We want to plot the Voltage over time from a Swiss AC socket.

AC in Switzerland alternates with 50 Hz and the voltage level is 230V RMS. That means, that the voltage peak is $230 V \times \sqrt{2} \approx 325 V$.

Tasks:
- Generate with the `linspace()` method an array `x_data` which contains 10000 points between 0 an 0.1: This will represent points in time.
- Use the general formula for a parametrised sine wave so calculate the Voltage for each point in time: y = A * sin(2 * pi * f * t + phi), where:
    - A is the amplitude of the wave
    - f is the frequency of the wave
    - t is the time
    - phi is the phase of the wave (which is irrelevant for us)

In [ ]:
# Given parameters
frequency = 50
amplitude = 325

# Generate the x data
x_data = np.linspace(0, 0.1, 10000) # 10000 points between 0 and 0.1 seconds
print(x_data)

# Generate the y data
y_data = amplitude * np.sin(2 * np.pi * frequency * x_data)
print(y_data)

# Plot the data
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.plot(x_data, y_data)
ax.set_xlabel('Time [s]')
ax.set_ylabel('Amplitude [V]')
ax.set_title('AC Voltage Signal of a Swiss Power Outlet')
ax.grid()

There are five periods during 100 ms, as expected for a 50 Hz signal.

# Exercise

Generate a RGB image and fill it with clever indexing, so that it shows the german (easy) or the swiss (harder) flag!

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

germany_flag = np.zeros((300, 500, 3), dtype=np.uint8)
# your code here


swiss_flag = np.zeros((500, 500, 3), dtype=np.uint8)
# your code here

plt.imshow(germany_flag)
# plt.imshow(swiss_flag)